### ISSUE TITLE
NEMO Crashing when adding custom icon

### ISSUE THREAD

**Issue by DeathBound** [MStr3am/NEMO#136]
Sir, there is a problem when adding custom icon, it is crashing when i select an icon then hit OK, its always crashing. help. thanks :)

**Comment by MStr3am** [comment]
which icon did you use?

**Comment by DeathBound** [comment]
Sir, It crashes when I use a 32x32 png icon which has transparency. I also tried 32x32 jpeg and still crashing..

and when im using 32x32 bmp and 32x32 ico file it says invalid icon file..

thanks

**Comment by MStr3am** [comment]
It needs to be an icon file containing atleast 1 image of size 32x32 and bit depth 8bpp.
if even one of the criteria don't match then would consider it an invalid icon file.
The criteria is there because I am replacing an existing icon inside the exe with the same specifications

need to add extra check to prevent the wrong file getting accepted.

**Comment by DeathBound** [comment]
Ok sir, I will try it and comment if something goes wrong.. thank you sir..

**Comment by DeathBound** [comment]
Sir, it works now. thank you so much :+1:
